name: "Test"
on:
  pull_request:
    types: [opened, reopened, edited]
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Run tests"
    steps:
      - uses: actions/checkout@v4
      - name: Create NATS cluster
        uses: onichandame/nats-action@master
        with:
          port: 4222
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: go.sum
      - name: "Show version"
        run: go version
      - name: "Run tests"
        run: go test -count 1 -timeout 30s -cover ./...
