$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - node_modules
  - pnpm-lock.yaml
  - .tsbuildinfo
  - .gitignore
  - dist
  - storybook-static
  - .next
  - .astro
  - drizzle
  - '**/*.svg'
words:
  - acst
  - aest
  - akst
  - astro
  - astrojs
  - autodocs
  - autoplay
  - awst
  - Beamer
  - Binni
  - branchname
  - bvaughn
  - Byrom
  - clsx
  - cmdk
  - codespace
  - codespaces
  - Colm
  - commitlint
  - consts
  - crossorigin
  - datetime
  - degit
  - Duarte
  - Elsakaan
  - Embla
  - esbenp
  - hookform
  - ianvs
  - ixahmedxi
  - jiti
  - lockb
  - lucide
  - Malyavko
  - Mintlify
  - neonctl
  - neondatabase
  - nextjs
  - nzst
  - orbitkit
  - Ornella
  - packagejson
  - pacocoursey
  - peduarte
  - quickstart
  - Ratelimit
  - shadcn
  - sslmode
  - starterkit
  - starterkits
  - stylesheet
  - tada
  - tailwindcss
  - thollander
  - todos
  - topbar
  - tsbuildinfo
  - tsconfigs
  - tsup
  - Tuite
  - turborepo
  - typecheck
  - typeof
  - typesafe
  - unkey
  - uploadthing
  - vaul
  - viewports
  - WITA
