[features]
seeds = false
skip-lint = false
[programs.devnet]
escrow = "GozEmwfidM8rN2HAFZQz26KJCNsUi81Vp7TYmNQJviSL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
